title: Learning Pentesting - !! UNDER DEVELOPEMENT !!
iconURL: /assets/logo.png
theme: jekyll-theme-hacker

# for a clean URL
permalink: :slug

collections:
  categories:
    output: true

social:
  twitter: mars_verdaguer
  github: pmarsverdaguer

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
#hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N